import { describe, expect, it } from 'vitest'
import { buildingDefinitions } from '../data/buildings'
import { derivePopulationCapacity, initialGameState, resolveConstructions, startConstruction, startUpgrade } from './rules'
import { gameStateSchema, migrateV1ToV2, migrateV2ToV3 } from '../persistence/save'
const builtCottage = resolveConstructions(startConstruction(initialGameState, 'city_plot_01', 'cottage', 0), 10_000)
describe('building upgrades', () => {
  it('starts Cottage level 1 upgrade with cost, target, and timestamps', () => { const state = startUpgrade(builtCottage, 'city_plot_01', 20_000); expect(state.wood).toBe(4800); expect(state.stone).toBe(4875); expect(state.plots.city_plot_01).toMatchObject({ status: 'upgrading', currentLevel: 1, targetLevel: 2, startedAt: 20_000, completesAt: 30_000 }) })
  it('rejects invalid, duplicate, max-level, and unaffordable upgrades', () => { expect(startUpgrade(initialGameState, 'city_plot_01', 1)).toBe(initialGameState); const upgrading = startUpgrade(builtCottage, 'city_plot_01', 1); expect(startUpgrade(upgrading, 'city_plot_01', 2)).toBe(upgrading); expect(startUpgrade(initialGameState, 'unknown', 1)).toBe(initialGameState); const max = { ...builtCottage, plots: { ...builtCottage.plots, city_plot_01: { id: 'city_plot_01', status: 'occupied' as const, buildingId: 'cottage' as const, level: 10 } } } as typeof builtCottage; expect(startUpgrade(max, 'city_plot_01', 1)).toBe(max); const poor = { ...builtCottage, wood: 0 }; expect(startUpgrade(poor, 'city_plot_01', 1)).toBe(poor) })
  it('resolves upgrades idempotently and keeps current population during upgrade', () => { const l3 = { ...builtCottage, plots: { ...builtCottage.plots, city_plot_01: { id: 'city_plot_01', status: 'occupied' as const, buildingId: 'cottage' as const, level: 3 } } } as typeof builtCottage; const up = startUpgrade(l3, 'city_plot_01', 1); expect(derivePopulationCapacity(up)).toBe(90); const done = resolveConstructions(up, 21_000); expect(done.plots.city_plot_01).toMatchObject({ status: 'occupied', level: 4 }); expect(derivePopulationCapacity(done)).toBe(120); expect(resolveConstructions(done, 30_000)).toBe(done) })
  it('supports concurrent upgrades and construction', () => { const second = resolveConstructions(startConstruction(initialGameState, 'city_plot_02', 'barracks', 0), 15_000); const both = startUpgrade({ ...second, plots: { ...second.plots, city_plot_01: builtCottage.plots.city_plot_01 } }, 'city_plot_01', 1); const resolved = resolveConstructions(both, 10_000); expect(resolved.plots.city_plot_01.status).toBe('upgrading'); expect(resolved.plots.city_plot_02.status).toBe('occupied') })
})
describe('ranks, population, and migrations', () => {
  it.each([[1, 'I'], [3, 'I'], [4, 'II'], [7, 'II'], [8, 'III'], [10, 'III']] as const)('maps level %s to Rank %s', (level, rank) => expect(buildingDefinitions.cottage.rankForLevel(level)).toBe(rank))
  it('derives population by current Cottage level', () => { expect(derivePopulationCapacity(builtCottage)).toBe(50); const level10 = { ...builtCottage, plots: { ...builtCottage.plots, city_plot_01: { id: 'city_plot_01' as const, status: 'occupied' as const, buildingId: 'cottage' as const, level: 10 } } } as typeof builtCottage; expect(derivePopulationCapacity(level10)).toBe(400) })
  it('migrates v2 visualRank saves to v3 and chains v1', () => { const v2 = { version: 2, wood: 700, stone: 650, plots: { city_plot_01: { id: 'city_plot_01', status: 'occupied', buildingId: 'cottage', level: 4, visualRank: 'I' } } }; const migrated = migrateV2ToV3(v2); expect(migrated?.plots.city_plot_01).toEqual({ id: 'city_plot_01', status: 'occupied', buildingId: 'cottage', level: 4 }); expect(gameStateSchema.safeParse(migrated).success).toBe(true); const v1 = migrateV2ToV3(migrateV1ToV2({ version: 1, wood: 500, stone: 500, plot: { id: 'city_plot_01', status: 'occupied', buildingId: 'cottage', level: 1, visualRank: 'I' } })); expect(v1?.version).toBe(3); expect(derivePopulationCapacity(v1!)).toBe(50) })
})
