import { describe, expect, it } from 'vitest'
import { buildingDefinitions } from '../data/buildings'
import { derivePopulationCapacity, initialGameState, resolveConstructions, startConstruction } from './rules'
import { gameStateSchema, migrateV1ToV2 } from '../persistence/save'
const at = (state: typeof initialGameState, id: string, building: string, now = 1000) => startConstruction(state, id, building, now)
describe('generic construction', () => {
  it('starts Cottage, Barracks, and Storehouse on arbitrary plots', () => { expect(at(initialGameState, 'city_plot_02', 'cottage').plots.city_plot_02.status).toBe('constructing'); expect(at(initialGameState, 'city_plot_03', 'barracks').plots.city_plot_03.status).toBe('constructing'); expect(at(initialGameState, 'city_plot_04', 'storehouse').plots.city_plot_04.status).toBe('constructing') })
  it('deducts costs and rejects insufficient resources or unsafe ids', () => { const state = at(initialGameState, 'city_plot_01', 'barracks'); expect(state.wood).toBe(850); expect(state.stone).toBe(900); const poor = { ...initialGameState, wood: 0 }; expect(startConstruction(poor, 'city_plot_01', 'cottage', 1)).toBe(poor); expect(startConstruction(initialGameState, 'unknown', 'cottage', 1)).toBe(initialGameState); expect(startConstruction(initialGameState, 'city_plot_01', 'unknown', 1)).toBe(initialGameState) })
  it('allows simultaneous construction and resolves only expired plots', () => { const a = at(initialGameState, 'city_plot_01', 'cottage'); const both = at(a, 'city_plot_02', 'barracks'); const one = resolveConstructions(both, 11_000); expect(one.plots.city_plot_01.status).toBe('occupied'); expect(one.plots.city_plot_02.status).toBe('constructing'); const all = resolveConstructions(both, 20_000); expect(all.plots.city_plot_01.status).toBe('occupied'); expect(all.plots.city_plot_02.status).toBe('occupied'); expect(resolveConstructions(all, 30_000)).toBe(all) })
  it('derives population from completed Cottages only', () => { const cottageState = resolveConstructions(at(initialGameState, 'city_plot_01', 'cottage'), 11_000); const two = resolveConstructions(at(at(initialGameState, 'city_plot_01', 'cottage'), 'city_plot_02', 'cottage'), 11_000); const mixed = resolveConstructions(at(at(initialGameState, 'city_plot_01', 'barracks'), 'city_plot_02', 'storehouse'), 20_000); expect(derivePopulationCapacity(initialGameState)).toBe(0); expect(derivePopulationCapacity(at(initialGameState, 'city_plot_01', 'cottage'))).toBe(0); expect(derivePopulationCapacity(cottageState)).toBe(50); expect(derivePopulationCapacity(two)).toBe(100); expect(derivePopulationCapacity(mixed)).toBe(0) })
})
describe('building ranks and migration', () => {
  it.each([[1, 'I'], [3, 'I'], [4, 'II'], [7, 'II'], [8, 'III'], [10, 'III']] as const)('maps level %s to Rank %s', (level, rank) => expect(buildingDefinitions.cottage.rankForLevel(level)).toBe(rank))
  it('migrates version 1 to version 2 and preserves the old plot', () => { const migrated = migrateV1ToV2({ version: 1, wood: 700, stone: 650, populationCapacity: 50, plot: { id: 'city_plot_01', status: 'occupied', buildingId: 'cottage', level: 1, visualRank: 'I' } }); expect(migrated?.wood).toBe(700); expect(migrated?.plots.city_plot_01.status).toBe('occupied'); expect(Object.values(migrated?.plots ?? {}).filter((plot) => plot.status === 'empty')).toHaveLength(5); expect(derivePopulationCapacity(migrated!)).toBe(50); expect(gameStateSchema.safeParse(migrated).success).toBe(true) })
  it('preserves constructing timestamps during migration', () => { const migrated = migrateV1ToV2({ version: 1, wood: 700, stone: 650, plot: { id: 'city_plot_01', status: 'constructing', buildingId: 'cottage', level: 1, visualRank: 'I', startedAt: 10, completesAt: 20 } }); expect(migrated?.plots.city_plot_01).toMatchObject({ status: 'constructing', startedAt: 10, completesAt: 20 }) })
})
