import { getBuildingDefinition, type BuildingId, type BuildingRank } from '../data/buildings'
export type PlotId = 'city_plot_01' | 'city_plot_02' | 'city_plot_03' | 'city_plot_04' | 'city_plot_05' | 'city_plot_06'
export const plotIds: PlotId[] = ['city_plot_01', 'city_plot_02', 'city_plot_03', 'city_plot_04', 'city_plot_05', 'city_plot_06']
export type Plot = { id: PlotId; status: 'empty' } | { id: PlotId; status: 'constructing'; buildingId: BuildingId; level: 1; startedAt: number; completesAt: number } | { id: PlotId; status: 'occupied'; buildingId: BuildingId; level: number } | { id: PlotId; status: 'upgrading'; buildingId: BuildingId; currentLevel: number; targetLevel: number; startedAt: number; completesAt: number }
export type GameStateData = { version: 3; wood: number; stone: number; plots: Record<PlotId, Plot> }
export const emptyPlots = (): Record<PlotId, Plot> => Object.fromEntries(plotIds.map((id) => [id, { id, status: 'empty' }])) as Record<PlotId, Plot>
export const initialGameState: GameStateData = { version: 3, wood: 5000, stone: 5000, plots: emptyPlots() }
export function startConstruction(state: GameStateData, plotId: string, buildingId: string, now: number): GameStateData { const plot = state.plots[plotId as PlotId]; const building = getBuildingDefinition(buildingId); if (!plot || plot.status !== 'empty' || !building || state.wood < building.constructionCost.wood || state.stone < building.constructionCost.stone) return state; const id = plotId as PlotId; return { ...state, wood: state.wood - building.constructionCost.wood, stone: state.stone - building.constructionCost.stone, plots: { ...state.plots, [id]: { id, status: 'constructing', buildingId: building.id, level: 1, startedAt: now, completesAt: now + building.constructionDurationMs } } } }
export function startUpgrade(state: GameStateData, plotId: string, now: number): GameStateData { const plot = state.plots[plotId as PlotId]; if (!plot || plot.status !== 'occupied' || plot.level >= 10) return state; const building = getBuildingDefinition(plot.buildingId); const targetLevel = plot.level + 1; const cost = building?.upgradeCosts[targetLevel]; if (!building || !cost || state.wood < cost.wood || state.stone < cost.stone) return state; const id = plotId as PlotId; return { ...state, wood: state.wood - cost.wood, stone: state.stone - cost.stone, plots: { ...state.plots, [id]: { id, status: 'upgrading', buildingId: plot.buildingId, currentLevel: plot.level, targetLevel, startedAt: now, completesAt: now + building.upgradeDurationMs(targetLevel) } } } }
export function resolveConstructions(state: GameStateData, now: number): GameStateData { const plots = { ...state.plots }; let changed = false; for (const id of plotIds) { const plot = plots[id]; if (plot.status === 'constructing' && plot.completesAt <= now) { plots[id] = { id, status: 'occupied', buildingId: plot.buildingId, level: 1 }; changed = true } else if (plot.status === 'upgrading' && plot.completesAt <= now) { plots[id] = { id, status: 'occupied', buildingId: plot.buildingId, level: plot.targetLevel }; changed = true } } return changed ? { ...state, plots } : state }
export function derivePopulationCapacity(state: Pick<GameStateData, 'plots'>): number { return Object.values(state.plots).reduce((total, plot) => { if (plot.status === 'empty' || plot.status === 'constructing') return total; const building = getBuildingDefinition(plot.buildingId); const level = plot.status === 'upgrading' ? plot.currentLevel : plot.level; return total + (building?.populationByLevel[level] ?? 0) }, 0) }
export function rankForPlot(plot: Plot): BuildingRank | undefined { if (plot.status === 'empty') return undefined; return getBuildingDefinition(plot.buildingId)?.rankForLevel(plot.status === 'upgrading' ? plot.currentLevel : plot.level) }
