import { getBuildingDefinition, type BuildingId, type BuildingRank } from '../data/buildings'
export type PlotId = 'city_plot_01' | 'city_plot_02' | 'city_plot_03' | 'city_plot_04' | 'city_plot_05' | 'city_plot_06'
export const plotIds: PlotId[] = ['city_plot_01', 'city_plot_02', 'city_plot_03', 'city_plot_04', 'city_plot_05', 'city_plot_06']
export type Plot = { id: PlotId; status: 'empty' } | { id: PlotId; status: 'constructing'; buildingId: BuildingId; level: number; visualRank: BuildingRank; startedAt: number; completesAt: number } | { id: PlotId; status: 'occupied'; buildingId: BuildingId; level: number; visualRank: BuildingRank }
export type GameStateData = { version: 2; wood: number; stone: number; plots: Record<PlotId, Plot> }
export const emptyPlots = (): Record<PlotId, Plot> => Object.fromEntries(plotIds.map((id) => [id, { id, status: 'empty' }])) as Record<PlotId, Plot>
export const initialGameState: GameStateData = { version: 2, wood: 1000, stone: 1000, plots: emptyPlots() }
export function startConstruction(state: GameStateData, plotId: string, buildingId: string, now: number): GameStateData { const plot = state.plots[plotId as PlotId]; const building = getBuildingDefinition(buildingId); if (!plot || plot.status !== 'empty' || !building || state.wood < building.constructionCost.wood || state.stone < building.constructionCost.stone) return state; const id = plotId as PlotId; return { ...state, wood: state.wood - building.constructionCost.wood, stone: state.stone - building.constructionCost.stone, plots: { ...state.plots, [id]: { id, status: 'constructing', buildingId: building.id, level: 1, visualRank: building.rankForLevel(1), startedAt: now, completesAt: now + building.constructionDurationMs } } } }
export function resolveConstructions(state: GameStateData, now: number): GameStateData { const plots = { ...state.plots }; let changed = false; for (const id of plotIds) { const plot = plots[id]; if (plot.status === 'constructing' && plot.completesAt <= now) { plots[id] = { id, status: 'occupied', buildingId: plot.buildingId, level: plot.level, visualRank: plot.visualRank }; changed = true } } return changed ? { ...state, plots } : state }
export function derivePopulationCapacity(state: Pick<GameStateData, 'plots'>): number { return Object.values(state.plots).reduce((total, plot) => { if (plot.status !== 'occupied') return total; const building = getBuildingDefinition(plot.buildingId); return total + (building?.populationCapacity ?? 0) }, 0) }
