import { z } from 'zod'
import { database } from './database'
import { emptyPlots, plotIds, type GameStateData, type Plot, type PlotId } from '../game/rules'
const plotSchema = z.discriminatedUnion('status', [z.object({ id: z.string(), status: z.literal('empty') }), z.object({ id: z.string(), status: z.literal('constructing'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), level: z.literal(1), startedAt: z.number(), completesAt: z.number() }), z.object({ id: z.string(), status: z.literal('occupied'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), level: z.number().int().min(1).max(10) }), z.object({ id: z.string(), status: z.literal('upgrading'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), currentLevel: z.number().int().min(1).max(9), targetLevel: z.number().int().min(2).max(10), startedAt: z.number(), completesAt: z.number() })])
export const gameStateSchema = z.object({ version: z.literal(3), wood: z.number().nonnegative(), stone: z.number().nonnegative(), plots: z.record(z.string(), plotSchema).refine((plots) => plotIds.every((id) => id in plots) && Object.keys(plots).every((id) => plotIds.includes(id as PlotId))) })
const v2PlotSchema = z.discriminatedUnion('status', [z.object({ id: z.literal('city_plot_01').or(z.string()), status: z.literal('empty') }), z.object({ id: z.string(), status: z.literal('constructing'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), level: z.literal(1), visualRank: z.enum(['I', 'II', 'III']), startedAt: z.number(), completesAt: z.number() }), z.object({ id: z.string(), status: z.literal('occupied'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), level: z.number().int().min(1).max(10), visualRank: z.enum(['I', 'II', 'III']) })])
const v2Schema = z.object({ version: z.literal(2), wood: z.number().nonnegative(), stone: z.number().nonnegative(), plots: z.record(z.string(), v2PlotSchema) })
const v1PlotSchema = z.discriminatedUnion('status', [z.object({ id: z.literal('city_plot_01'), status: z.literal('empty') }), z.object({ id: z.literal('city_plot_01'), status: z.literal('constructing'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), level: z.literal(1), visualRank: z.enum(['I', 'II', 'III']), startedAt: z.number(), completesAt: z.number() }), z.object({ id: z.literal('city_plot_01'), status: z.literal('occupied'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), level: z.number().int().min(1).max(10), visualRank: z.enum(['I', 'II', 'III']) })])
const v1Schema = z.object({ version: z.literal(1), wood: z.number().nonnegative(), stone: z.number().nonnegative(), plot: v1PlotSchema.optional(), populationCapacity: z.number().nonnegative().optional() })
function stripRank(plot: z.infer<typeof v2PlotSchema>): Plot { if (plot.status === 'empty') return { id: plot.id as PlotId, status: 'empty' }; if (plot.status === 'constructing') return { id: plot.id as PlotId, status: 'constructing', buildingId: plot.buildingId, level: 1, startedAt: plot.startedAt, completesAt: plot.completesAt }; return { id: plot.id as PlotId, status: 'occupied', buildingId: plot.buildingId, level: plot.level } }
export function migrateV2ToV3(value: unknown): GameStateData | null { const parsed = v2Schema.safeParse(value); if (!parsed.success) return null; const plots = emptyPlots(); for (const id of plotIds) if (parsed.data.plots[id]) plots[id] = stripRank(parsed.data.plots[id]); return { version: 3, wood: parsed.data.wood, stone: parsed.data.stone, plots } }
export function migrateV1ToV2(value: unknown): unknown { const parsed = v1Schema.safeParse(value); if (!parsed.success) return null; const plots = emptyPlots(); if (parsed.data.plot) plots.city_plot_01 = { ...parsed.data.plot }; return { version: 2, wood: parsed.data.wood, stone: parsed.data.stone, plots } }
const key = 'game-state'
export async function loadGameState(): Promise<GameStateData | null> { const row = await database.settings.get(key); if (!row) return null; try { const raw: unknown = JSON.parse(row.value); const current = gameStateSchema.safeParse(raw); if (current.success) return current.data as GameStateData; const v2 = migrateV2ToV3(raw); if (v2) return v2; const v1 = migrateV1ToV2(raw); return v1 ? migrateV2ToV3(v1) : null } catch { return null } }
export async function saveGameState(state: GameStateData) { await database.settings.put({ key, value: JSON.stringify(state) }) }
