import { z } from 'zod'
import { database } from './database'
import { initialGameState, type GameStateData } from '../game/rules'
import { getBuildingDefinition } from '../data/buildings'
const ids=['cottage','barracks','storehouse','castle','research_lab','walls'] as const
const structure=z.object({buildingId:z.enum(ids),level:z.number().int().min(1).max(10)})
const up=z.object({buildingId:z.enum(ids),currentLevel:z.number().int().min(1).max(9),targetLevel:z.number().int().min(2).max(10),startedAt:z.number(),completesAt:z.number()}).refine(v=>v.targetLevel===v.currentLevel+1)
const plot=z.discriminatedUnion('status',[z.object({id:z.string(),status:z.literal('empty')}),z.object({id:z.string(),status:z.literal('constructing'),buildingId:z.enum(ids),level:z.literal(1),startedAt:z.number(),completesAt:z.number()}),z.object({id:z.string(),status:z.literal('occupied'),buildingId:z.enum(ids),level:z.number().int().min(1).max(10)}),z.object({id:z.string(),status:z.literal('upgrading'),buildingId:z.enum(ids),currentLevel:z.number().int().min(1).max(9),targetLevel:z.number().int().min(2).max(10),startedAt:z.number(),completesAt:z.number()}).refine(v=>v.targetLevel===v.currentLevel+1)])
export const gameStateSchema=z.object({version:z.literal(4),wood:z.number().nonnegative(),stone:z.number().nonnegative(),city:z.object({plots:z.record(z.string(),plot),castle:structure.or(up),researchLab:structure.or(up),walls:structure.or(up)}),plots:z.record(z.string(),plot).optional()})
export function migrateV3ToV4(value:unknown):GameStateData|null{const v=value as {version?:number;wood?:number;stone?:number;plots?:Record<string,any>};if(v.version!==3||typeof v.wood!=='number'||typeof v.stone!=='number'||!v.plots)return null;const plots={...initialGameState.city.plots};let active:any;for(const id of Object.keys(plots).slice(0,6)){const p=v.plots[id];if(!p)continue;if(p.status==='occupied'||p.status==='empty')plots[id as keyof typeof plots]=p;if((p.status==='constructing'||p.status==='upgrading')&&(!active||p.startedAt<active.startedAt))active={...p,id}}let wood=v.wood,stone=v.stone;if(active){const id=active.id as keyof typeof plots;plots[id]=active;for(const p of Object.values(v.plots)){if(p===active)continue;const b=getBuildingDefinition(p.buildingId);const c=p.status==='constructing'?b?.constructionCost:b?.upgradeCosts?.[p.targetLevel];if((p.status==='constructing'||p.status==='upgrading')&&c){wood+=c.wood;stone+=c.stone}}}return {...initialGameState,wood,stone,city:{...initialGameState.city,plots},plots}}
const key='game-state';export async function loadGameState():Promise<GameStateData|null>{const row=await database.settings.get(key);if(!row)return null;try{const raw=JSON.parse(row.value);const parsed=gameStateSchema.safeParse(raw);return parsed.success?parsed.data as GameStateData:migrateV3ToV4(raw)}catch{return null}}
export async function saveGameState(state:GameStateData){await database.settings.put({key,value:JSON.stringify(state)})}
let saveQueue:Promise<void>=Promise.resolve();export function queueSaveGameState(state:GameStateData){const op=saveQueue.catch(()=>undefined).then(()=>saveGameState(state));saveQueue=op.catch(()=>undefined);return op}
export function migrateV1ToV2(value:unknown){const v=value as any;if(v?.version!==1||!v.plot)return null;return {...v,version:2,plots:{[v.plot.id]:v.plot},plot:undefined}}
export function migrateV2ToV3(value:unknown){const v=value as any;if(v?.version!==2)return null;return {...v,version:3,plots:Object.fromEntries(Object.entries(v.plots??{}).map(([k,p]:any)=>[k,{...p,visualRank:undefined}]))}}
