import { z } from 'zod'
import { database } from './database'
import { emptyPlots, plotIds, type GameStateData, type Plot } from '../game/rules'
const plotSchema = z.discriminatedUnion('status', [z.object({ id: z.string(), status: z.literal('empty') }), z.object({ id: z.string(), status: z.literal('constructing'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), level: z.number().int().min(1).max(10), visualRank: z.enum(['I', 'II', 'III']), startedAt: z.number(), completesAt: z.number() }), z.object({ id: z.string(), status: z.literal('occupied'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), level: z.number().int().min(1).max(10), visualRank: z.enum(['I', 'II', 'III']) })])
export const gameStateSchema = z.object({ version: z.literal(2), wood: z.number().nonnegative(), stone: z.number().nonnegative(), plots: z.record(z.string(), plotSchema).refine((plots) => plotIds.every((id) => id in plots) && Object.keys(plots).every((id) => plotIds.includes(id as PlotId))) })
const v1PlotSchema = z.discriminatedUnion('status', [z.object({ id: z.literal('city_plot_01'), status: z.literal('empty') }), z.object({ id: z.literal('city_plot_01'), status: z.literal('constructing'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), level: z.number().int().min(1).max(10), visualRank: z.enum(['I', 'II', 'III']), startedAt: z.number(), completesAt: z.number() }), z.object({ id: z.literal('city_plot_01'), status: z.literal('occupied'), buildingId: z.enum(['cottage', 'barracks', 'storehouse']), level: z.number().int().min(1).max(10), visualRank: z.enum(['I', 'II', 'III']) })])
const v1Schema = z.object({ version: z.literal(1), wood: z.number().nonnegative(), stone: z.number().nonnegative(), plot: v1PlotSchema.optional(), populationCapacity: z.number().nonnegative().optional() })
type PlotId = (typeof plotIds)[number]
export function migrateV1ToV2(value: unknown): GameStateData | null { const parsed = v1Schema.safeParse(value); if (!parsed.success) return null; const plots = emptyPlots(); if (parsed.data.plot) plots.city_plot_01 = parsed.data.plot as Plot; return { version: 2, wood: parsed.data.wood, stone: parsed.data.stone, plots } }
const key = 'game-state'
export async function loadGameState(): Promise<GameStateData | null> { const row = await database.settings.get(key); if (!row) return null; try { const raw: unknown = JSON.parse(row.value); const current = gameStateSchema.safeParse(raw); if (current.success) return current.data as GameStateData; return migrateV1ToV2(raw) } catch { return null } }
export async function saveGameState(state: GameStateData) { await database.settings.put({ key, value: JSON.stringify(state) }) }
