import { useCallback, useEffect, useState } from 'react'
import { cottage } from './data/buildings'
import { PixiViewport } from './game/rendering/PixiViewport'
import { useGameStore } from './state/gameStore'

const views = ['city', 'field', 'world'] as const
export default function App() { const game = useGameStore(); const [popup, setPopup] = useState(false); const [, tick] = useState(0); const openPlot = useCallback(() => setPopup(true), [])
  useEffect(() => { void game.hydrate() }, [])
  useEffect(() => { const id = window.setInterval(() => { tick((n) => n + 1); void game.resolve() }, 1000); return () => window.clearInterval(id) }, [game.resolve])
  const remaining = game.plot.status === 'constructing' ? Math.max(0, Math.ceil((game.plot.completesAt - Date.now()) / 1000)) : 0
  const build = async () => { await game.beginConstruction(); setPopup(false) }
  return <main className="mx-auto flex min-h-screen max-w-5xl flex-col gap-5 bg-stone-950 px-6 py-8 text-stone-100"><header className="border-b border-stone-700 pb-5"><p className="text-xs uppercase tracking-[0.2em] text-stone-400">City View</p><h1 className="mt-2 text-3xl font-bold">Battle for Altarin</h1><div className="mt-4 flex gap-5 text-sm"><span>Wood: {game.wood}</span><span>Stone: {game.stone}</span><span>Population Capacity: {game.populationCapacity}</span></div></header><nav aria-label="Game views" className="flex gap-2">{views.map((view) => <button className={`rounded px-4 py-2 capitalize ${game.activeView === view ? 'bg-stone-200 text-stone-950' : 'bg-stone-800 text-stone-200'}`} key={view} onClick={() => game.selectView(view)} type="button">{view}</button>)}</nav>{game.hydrated && <PixiViewport plot={game.plot} onPlotClick={openPlot} />}{game.plot.status === 'constructing' && <p role="status" className="text-center text-amber-200">Cottage construction: {remaining}s remaining</p>}{popup && <div role="dialog" aria-label="Build Cottage" className="fixed inset-0 grid place-items-center bg-black/60"><div className="w-80 rounded-lg bg-stone-900 p-6 shadow-xl"><h2 className="text-xl font-semibold">Build Cottage</h2><p className="mt-3 text-sm text-stone-300">Cost: 100 Wood · 50 Stone</p><p className="text-sm text-stone-300">Build time: 10 seconds</p><p className="text-sm text-stone-300">Population: +50 capacity</p><div className="mt-5 flex justify-end gap-2"><button className="rounded bg-stone-700 px-3 py-2" onClick={() => setPopup(false)} type="button">Cancel</button><button className="rounded bg-amber-700 px-3 py-2 disabled:opacity-40" disabled={game.wood < cottage.constructionCost.wood || game.stone < cottage.constructionCost.stone} onClick={() => void build()} type="button">Build</button></div></div></div>}</main>
}
